## Use this file if there is a dependency of python related packages
- hosts: all
  gather_facts: False

  tasks:
  - name: install python 2
    become: yes
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  - name: install python-apt
    become: yes
    command: apt-get install python-apt -y
